# Generated by Django 5.2.15 on 2026-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
